### ISSUE TITLE
Getting error AttributeError: 'module' object has no attribute 'control_flow_ops'

### ISSUE THREAD

**Issue by shaktisd** [dandxy89/DeepLearning_MachineLearning#9]
python imdb_embedding_w2v.py
Using TensorFlow backend.
Loading Data...
Tokenising...
Training a Word2vec model...
Transform the Data...
Setting up Arrays for Keras Embedding Layer...
Creating Datesets...
Pad sequences (samples x time)
('X_train shape:', (25000, 100))
('X_test shape:', (25000, 100))
Convert labels to Numpy Sets...
Defining a Simple Sequential Keras Model...
Traceback (most recent call last):
  File "imdb_embedding_w2v.py", line 205, in <module>
    model.add(Dropout(0.3))
  File "/home/shakti/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/home/shakti/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/shakti/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/shakti/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/shakti/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/layers/core.py", line 90, in call
    x = K.in_train_phase(K.dropout(x, self.p, noise_shape), x)
  File "/home/shakti/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1304, in in_train_phase
    x = tf.python.control_flow_ops.cond(tf.cast(_LEARNING_PHASE, 'bool'),
AttributeError: 'module' object has no attribute 'control_flow_ops'

Using following version of Keras
pip show keras
---
Metadata-Version: 2.0
Name: Keras
Version: 1.1.0

**Comment by dandxy89** [comment]
Likely an error upstream with Tensorflow due to refactoring of the Python scripts.

Will take a look tomorrow.

**Comment by shaktisd** [comment]
@dandxy89 Yeah , it got resolved after reverting to Tensorflow 0.10 . Thanks

**Comment by dandxy89** [comment]
@shaktisd What version of TF did you have?

**Comment by shaktisd** [comment]
Earlier I was having export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl

then I downgraded it to

export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

**Comment by dandxy89** [comment]
Thanks for letting me know, the fix will need to be applied to Keras since that is where the error is occurring. 

The build of TF is currently 0.9 when testing Keras so they will not know till then.

If you have time, raise it as an issue on the issue log.
